name: Build with Cmake & MSVC
run-name: building & testing with Cmake & MSVC
on:
  push:
    branches:
      - 'build-msvc/**'
      - 'build/**'
jobs:
  Build-with-cmake-msvc:
    runs-on: windows-latest
    timeout-minutes: 40
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: cmake
        shell: pwsh
        run: |
          New-Item .\Work -ItemType Directory
          cd .\Work
          cmake.exe ..
      - name: cmake --build
        shell: pwsh
        run: |
          cd .\Work
          cmake.exe --build .

      - name: test kpathsea
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/kpathsea
          $srcdir/tests/cnfline.test
          $srcdir/tests/cnfnewline.test
          $srcdir/tests/cnfnull.test || echo "**\n** failed: cnfnull.test\n**"
          $srcdir/tests/cnfprog.test
          # $srcdir/tests/kpseaccess.test
          # $srcdir/tests/kpsereadlink.test
          $srcdir/tests/kpsestat.test
          $srcdir/tests/kpsewhich.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - name: test dviout-util
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/dviout-util
          cp $srcdir/tests/put.dump.dvi ./putΔДदダ打다𝕯🎉.dump.dvi
          $srcdir/dvispc.test
          $srcdir/chkdvifont.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - run: echo "⛄ This job's status is ${{ job.status }}."
