name: Build with Cmake & MSVC
run-name: ${{ github.actor }} is building and testing with Cmake & MSVC
on:
  push:
    branches:
      - 'build-msvc/**'
jobs:
  Build-with-cmake-msvc:
    runs-on: windows-latest
    timeout-minutes: 40
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: cmake
        shell: pwsh
        run: |
          New-Item .\Work -ItemType Directory
          cd .\Work
          cmake.exe ..
      - name: cmake --build
        shell: pwsh
        run: |
          cd .\Work
          cmake.exe --build .

      - name: test kpathsea
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/kpathsea
          $srcdir/tests/kpsewhich.test
          $srcdir/tests/kpsestat.test
          $srcdir/tests/cnfline.test
          $srcdir/tests/cnfnewline.test
          $srcdir/tests/cnfprog.test
          # $srcdir/tests/kpseaccess.test
          # $srcdir/tests/kpsereadlink.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - name: test dvipdfm-x
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/dvipdfm-x
          $srcdir/xdvipdfmx.test
          $srcdir/xdvipdfm-ann.test
          $srcdir/xdvipdfm-bad.test
          $srcdir/xdvipdfm-bb.test
          $srcdir/xdvipdfm-bkm.test
          $srcdir/xdvipdfm-psz.test
          $srcdir/xdvipdfm-ptx.test
          $srcdir/xdvipdfm-res.test
          $srcdir/xdvipdfm-rev.test
          $srcdir/xdvipdfm-ttc.test
          # $srcdir/dvipdfmx-upjf.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"
          SOURCE_DATE_EPOCH: "1588474800"

      - name: test dvips
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/dvipsk
          $srcdir/test-dvips.test
          $srcdir/test-afm2tfm.test
          $srcdir/beginfontk1.test
          $srcdir/eepic-nan.test
          $srcdir/pfbincl.test
          $srcdir/same-name.test
          $srcdir/test-missing-image.test
          $srcdir/test-overflow-buffers.test
          $srcdir/uptex-vf.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"
          SOURCE_DATE_EPOCH: "1588474800"

      - name: test makejvf
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/makejvf
          $srcdir/makejvf.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - name: test mendex
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/mendexk
          $srcdir/tests/mendex.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - name: test upmendex
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/upmendex
          $srcdir/tests/upmendex.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - name: test bibtex-x
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/bibtex-x
          $srcdir/tests/bibtex8.test
          # $srcdir/tests/bibtex8-char.test
          # $srcdir/tests/bibtex8-sort.test
          $srcdir/tests/bibtexu.test
          # $srcdir/tests/bibtexu-basic.test
          # $srcdir/tests/bibtexu-range.test
          # $srcdir/tests/bibtexu-char.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"
#      - name: test bibtex-x, max_print_line=99
#        shell: bash
#        run: |
#          cd ./Work
#          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/bibtex-x
#          $srcdir/tests/bibtexu-sort.test
#        env:
#          srcroot: "../source"
#          TEXMFCNF: "../source/texk/kpathsea/tests/windows"
#          max_print_line: "99"

      - name: test dviout-util
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/dviout-util
          $srcdir/dvispc.test
          $srcdir/chkdvifont.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - name: test dvi2tty
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/dvi2tty DVI2TTY_TREE=dvi2tty-src
          $srcdir/disdvi.test
          $srcdir/dvi2tty.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - name: test seetex
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/seetexk
          $srcdir/seetexk.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - name: test dvidvi
        shell: bash
        run: |
          cd ./Work
          export BinDir=./Debug/bin ExeExt=.exe srcdir=../source/texk/dvidvi
          $srcdir/dvidvi.test
        env:
          srcroot: "../source"
          TEXMFCNF: "../source/texk/kpathsea/tests/windows"

      - run: echo "⛄ This job's status is ${{ job.status }}."
