name: Build on MacOS
run-name: building & testing on MacOS
on:
  push:
    branches:
      - 'build-macos/**'
      - 'build/**'
      - 'master'
jobs:
  Build-on-macos:
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch [ ${{ github.ref }} ]  Repository [ ${{ github.repository }} ]"
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: make libs
        shell: bash
        run: |
          mkdir -p ./source/Work/libs/{zlib,libpng,libpaper}
          cd ${{ github.workspace }}/source/Work/libs/zlib
          ../../../libs/zlib/configure
          make
          make check
          cd ${{ github.workspace }}/source/Work/libs/libpng
          ../../../libs/libpng/configure
          make
          make check

      - name: make kpathsea, ptexenc
        shell: bash
        run: |
          mkdir -p ./source/Work/texk/{kpathsea,ptexenc}
          cd ${{ github.workspace }}/source/Work/texk/kpathsea
          ../../../texk/kpathsea/configure
          make
          make check || cat tests/kpsesafe.log
          cd ${{ github.workspace }}/source/Work/texk/ptexenc
          ../../../texk/ptexenc/configure
          make

      - name: dviout-util
        shell: bash
        run: |
          mkdir -p ./source/Work/texk/dviout-util
          cd ./source/Work/texk/dviout-util
          ../../../texk/dviout-util/configure
          make
          make check || cat ./dvispc.log

      - run: echo "⛄ This job's status is ${{ job.status }}."
